"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveFloorPlan } from "@/app/actions";
import type { FloorPlan } from "@/lib/floorplan-schema";
import type { User } from "@supabase/supabase-js";

interface FloorPlanWithPrompt extends FloorPlan {
  __prompt?: string;
}

interface PropertiesSidebarProps {
  floorPlan: FloorPlan | null;
  user: User | null;
}

export default function PropertiesSidebar({ floorPlan, user }: PropertiesSidebarProps) {
  const router = useRouter();
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [exporting, setExporting] = useState(false);

  const rooms = floorPlan?.rooms ?? [];
  const totalArea = floorPlan?.totalArea ?? 0;
  const bedrooms = rooms.filter((r) => r.type === "bedroom" || r.type === "master_bedroom").length;
  const bathrooms = rooms.filter((r) => r.type === "bathroom" || r.type === "ensuite").length;

  function handleSave() {
    if (!floorPlan) return;
    if (!user) {
      router.push("/login");
      return;
    }
    setSaveStatus("saving");
    setError(null);
    startTransition(async () => {
      try {
        const promptText = (floorPlan as FloorPlanWithPrompt).__prompt ?? "Untitled plan";
        await saveFloorPlan(promptText, promptText, floorPlan);
        setSaveStatus("saved");
        setTimeout(() => setSaveStatus("idle"), 2500);
      } catch (err: unknown) {
        setSaveStatus("error");
        setError(err instanceof Error ? err.message : "Failed to save");
      }
    });
  }

  async function handleExportPDF() {
    if (!floorPlan) return;
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

      // Page sized 297×210mm; pad 15mm
      const pageW = 297;
      const pageH = 210;
      const pad = 15;
      const availW = pageW - pad * 2;
      const availH = pageH - pad * 2 - 20; // header space

      // Compute bounding box (px)
      const xs = rooms.map((r) => r.x);
      const ys = rooms.map((r) => r.y);
      const xe = rooms.map((r) => r.x + r.width);
      const ye = rooms.map((r) => r.y + r.height);
      const minX = Math.min(...xs);
      const minY = Math.min(...ys);
      const planW = Math.max(...xe) - minX;
      const planH = Math.max(...ye) - minY;
      const scale = Math.min(availW / planW, availH / planH);
      const offX = pad + (availW - planW * scale) / 2;
      const offY = pad + 20 + (availH - planH * scale) / 2;

      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text("Archy AI Floor Plan", pad, pad + 8);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.text(`Total area: ${totalArea} m²  ·  Rooms: ${rooms.length}`, pad, pad + 14);

      // Rooms
      rooms.forEach((room) => {
        const x = offX + (room.x - minX) * scale;
        const y = offY + (room.y - minY) * scale;
        const w = room.width * scale;
        const h = room.height * scale;

        doc.setDrawColor(0);
        doc.setFillColor(245, 245, 245);
        doc.rect(x, y, w, h, "FD");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.text(room.label, x + w / 2, y + h / 2, { align: "center" });

        const m2 = Math.round((room.width * room.height) / 2500);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.text(`${m2} m²`, x + w / 2, y + h / 2 + 4, { align: "center" });
      });

      // Doors as gaps in walls — draw thicker white line
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(0.8);
      (floorPlan.doors ?? []).forEach((door) => {
        const room = rooms.find((r) => r.id === door.roomId);
        if (!room) return;
        const x = offX + (room.x - minX) * scale;
        const y = offY + (room.y - minY) * scale;
        const w = room.width * scale;
        const h = room.height * scale;
        const gap = 4;
        const p = door.position;
        if (door.wall === "top") doc.line(x + w * p - gap / 2, y, x + w * p + gap / 2, y);
        if (door.wall === "bottom") doc.line(x + w * p - gap / 2, y + h, x + w * p + gap / 2, y + h);
        if (door.wall === "left") doc.line(x, y + h * p - gap / 2, x, y + h * p + gap / 2);
        if (door.wall === "right") doc.line(x + w, y + h * p - gap / 2, x + w, y + h * p + gap / 2);
      });

      doc.setLineWidth(0.2);
      doc.setDrawColor(150);
      doc.setFontSize(7);
      doc.text(`Generated by Archy AI · ${new Date().toLocaleDateString()}`, pageW - pad, pageH - pad / 2, { align: "right" });

      doc.save(`archy-ai-floor-plan-${Date.now()}.pdf`);
    } catch (err: unknown) {
      setError(`Export failed: ${err instanceof Error ? err.message : "unknown error"}`);
    } finally {
      setExporting(false);
    }
  }

  return (
    <aside className="hidden md:flex w-[320px] shrink-0 border-l border-border bg-background flex-col h-full">
      {/* Header */}
      <div className="h-[60px] px-4 border-b border-border flex items-center justify-between shrink-0">
        <p className="text-sm font-bold text-foreground">Properties</p>
        {user && (
          <Link
            href="/profile"
            className="text-[11px] font-semibold text-muted-foreground hover:text-foreground"
          >
            {user.email?.split("@")[0] ?? "Account"}
          </Link>
        )}
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-5">
        {!floorPlan ? (
          <div className="text-center pt-12">
            <p className="text-sm text-muted-foreground">
              Generate a floor plan to see its properties here.
            </p>
          </div>
        ) : (
          <>
            {/* Summary */}
            <div>
              <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-2">
                Overview
              </p>
              <div className="grid grid-cols-3 gap-2">
                <Stat label="Total" value={`${totalArea}`} unit="m²" />
                <Stat label="Beds" value={`${bedrooms}`} />
                <Stat label="Baths" value={`${bathrooms}`} />
              </div>
            </div>

            {/* Rooms */}
            <div>
              <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-2">
                Rooms ({rooms.length})
              </p>
              <div className="flex flex-col gap-1">
                {rooms.map((room) => {
                  const m2 = Math.round((room.width * room.height) / 2500);
                  return (
                    <div
                      key={room.id}
                      className="flex items-center justify-between px-3 py-2 rounded-lg bg-secondary/40 border border-border hover:bg-secondary transition-colors"
                    >
                      <div className="min-w-0">
                        <p className="text-xs font-semibold text-foreground truncate">
                          {room.label}
                        </p>
                        <p className="text-[10px] text-muted-foreground capitalize">
                          {room.type.replace(/_/g, " ")}
                        </p>
                      </div>
                      <span className="text-[11px] font-bold text-muted-foreground shrink-0 ml-2">
                        {m2} m²
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Doors / Windows count */}
            <div className="grid grid-cols-2 gap-2">
              <Stat label="Doors" value={`${floorPlan.doors?.length ?? 0}`} />
              <Stat label="Windows" value={`${floorPlan.windows?.length ?? 0}`} />
            </div>
          </>
        )}

        {error && (
          <div className="px-3 py-2.5 bg-red-950/30 border border-red-900/30 text-red-400 text-xs rounded-xl">
            {error}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-border shrink-0 bg-card flex flex-col gap-2">
        <button
          onClick={handleSave}
          disabled={!floorPlan || saveStatus === "saving" || isPending}
          className={`w-full py-2.5 rounded-xl text-xs font-semibold transition-all ${
            saveStatus === "saved"
              ? "bg-emerald-500/10 text-emerald-500 border border-emerald-500/30"
              : "bg-foreground text-background hover:opacity-90 disabled:opacity-40"
          }`}
        >
          {saveStatus === "saving" || isPending
            ? "Saving..."
            : saveStatus === "saved"
            ? "✓ Saved"
            : !user
            ? "Sign in to save"
            : "Save plan"}
        </button>

        <button
          onClick={handleExportPDF}
          disabled={!floorPlan || exporting}
          className="w-full py-2.5 rounded-xl text-xs font-semibold bg-secondary hover:bg-muted border border-border text-foreground transition-colors disabled:opacity-40"
        >
          {exporting ? "Exporting..." : "Export PDF"}
        </button>
      </div>
    </aside>
  );
}

function Stat({ label, value, unit }: { label: string; value: string; unit?: string }) {
  return (
    <div className="px-3 py-2.5 rounded-xl bg-secondary/40 border border-border">
      <p className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
        {label}
      </p>
      <p className="text-base font-bold text-foreground mt-0.5">
        {value}
        {unit && <span className="text-[10px] font-medium text-muted-foreground ml-0.5">{unit}</span>}
      </p>
    </div>
  );
}
