export default function PrivacyPage() {
  return (
    <main className="flex-1 max-w-3xl mx-auto px-6 py-20">
      <h1 className="text-4xl font-extrabold tracking-tight mb-8">Privacy Policy</h1>
      
      <div className="prose prose-neutral dark:prose-invert space-y-8 text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">1. Data Collection</h2>
          <p>
            We collect information you provide directly to us, such as when you create an account using OAuth (Google/GitHub), generate floor plans, or contact support. This includes your name, email address, and profile picture.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">2. How We Use Data</h2>
          <p>
            We use your data to provide and improve Archy AI&apos;s services, communicate with you, and personalize your experience. We do not sell your personal data to third parties.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">3. Content Storage</h2>
          <p>
            Floor plans generated by Archy AI are stored securely in our database. You can delete your projects at any time from your dashboard.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">4. Cookies</h2>
          <p>
            We use cookies for authentication and to maintain your session state. You can control cookie preferences through your browser settings.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">5. Security</h2>
          <p>
            We take reasonable measures to protect your personal information from loss, theft, and unauthorized access.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">6. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact us through our community channels.
          </p>
        </section>

        <div className="pt-12 border-t border-border">
          <p className="text-xs">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </main>
  );
}
