export default function TermsPage() {
  return (
    <main className="flex-1 max-w-3xl mx-auto px-6 py-20">
      <h1 className="text-4xl font-extrabold tracking-tight mb-8">Terms of Service</h1>
      
      <div className="prose prose-neutral dark:prose-invert space-y-8 text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Archy AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">2. Description of Service</h2>
          <p>
            Archy AI is an AI-powered floor plan generation platform. We provide tools for creating 2D blueprints and 3D visualizations based on natural language prompts.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">3. User Responsibilities</h2>
          <p>
            You are responsible for any content you generate using Archy AI. You must not use the service for any illegal or unauthorized purpose. You agree to comply with all local laws regarding online conduct and acceptable content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">4. Intellectual Property</h2>
          <p>
            The designs generated by Archy AI are for your personal and professional use. However, Archy AI retains ownership of the underlying AI models and proprietary layout algorithms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">5. Limitation of Liability</h2>
          <p>
            Archy AI is provided &quot;as is&quot; without warranty of any kind. We are not responsible for any architectural errors, structural inaccuracies, or losses resulting from the use of generated plans. Always consult a licensed professional before starting any construction.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-foreground mb-4">6. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Your continued use of the service constitutes acceptance of the updated terms.
          </p>
        </section>

        <div className="pt-12 border-t border-border">
          <p className="text-xs">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </main>
  );
}
